---
title: "report"
format: html
---

# Intro

## Visuals Covered

[ ] Total participants over time (with gender comparisons) *displayed as a stacked bar chart*

[ ] Official finish times for overall winners over time *displayed as a line chart*

[ ] Between-Gender comparisons of official finish times per age group *displayed as density ridge plot*

## Data

All data displayed represented is taken form the publicly available repository ["Boston Marathon Data"](https://github.com/adrian3/Boston-Marathon-Data-Project/tree/master)


```{r}
#| include: false
library(ggforce)
library(ggridges)
library(dplyr)
library(broom)
library(lubridate)
library(patchwork)
library(tidyverse)
library(purrr)
library(readr)
base_url <- "https://raw.githubusercontent.com/adrian3/Boston-Marathon-Data-Project/refs/heads/master/"

# years <- 1897:2019
years <- c(1897:1900, 2001, 2010)
file_urls <- paste0(base_url, "results", years, ".csv")

combined_data <- file_urls %>%
  set_names(years) %>% 
  map_dfr(read_csv, .id = "Year")
```

# Visuals

## Total participants over time (with gender comparisons)

```{r}
total_per_year <- combined_data |> 
  count(Year, gender) |>
  group_by(Year)

historical_participants <- total_per_year |>
  ggplot(aes(x=n, y=Year, fill=gender)) +
  geom_bar(position="stack", stat="identity")

total_per_year |>
  ggplot(aes(x=n, y=Year, fill=gender)) +
  geom_bar(position="stack", stat="identity") +
  labs(title="A) Total Participants per Year") +
  scale_x_time(name="Total Participants") +
  scale_y_discrete(name="Race Year")
```

## Official finish times for overall winners over time

```{r}
overall_winners <- combined_data |>
  filter(gender_result==1)

overall_bests <- overall_winners |>
  ggplot(aes(x=Year, y=official_time, color=gender, group=gender)) + 
  geom_point()
```

```{r}
combined_data |>
  ggplot(aes(x=factor(Year), y=official_time, color=gender, group=gender)) + 
  geom_line() + 
  geom_point()
```

## Between-Gender comparisons of official finish times per age group

```{r}
gender_finish_densities <- combined_data |>
  ggplot(aes(x=official_time, y=Year, color=gender, fill=gender)) +
  geom_density_ridges()

combined_data |>
  ggplot(aes(x=official_time, y=Year, color=gender, fill=gender)) +
  geom_density_ridges(alpha=0.4) +
  labs(title="B) Density ridges of official finish times") +
  guides(
    color = guide_legend(title="Gender", override.aes = list(alpha = 1)),
    fill = guide_legend(title="Gender", override.aes = list(alpha = 1))
  ) +
  scale_x_time(name="Official Finish Time") +
  scale_y_discrete(name="")
```

## Compiled Presentation

```{r}
#| fig-width: 11
#| fig-height: 5
#| out-width: "100%"

((historical_participants + gender_finish_densities) / overall_bests) +
  plot_layout(guides = "collect")
```