---
title: "report"
format: gfm
---

```{r}
library(dplyr)
library(lubridate)
library(jsonlite)
library(ggforce)
library(ggplot2)
library(tidyverse)
library(patchwork)

flatten_json <- function(json_data, melted_cols) {
  json_table <-
      bind_rows(
      lapply(json_data, function(months) {
        bind_rows(
          lapply(months, function(x) as.data.frame(x)), .id = "month")
        }
      ), 
    .id = "year")
  
  return(
    pivot_longer(
      data = json_table,
      cols = melted_cols,
      names_to = "type",
      values_to = "count"
    ) |>
    mutate(date = 
             if(is.numeric(month)) { make_date(year = year, month = month, day = 1) }
             else {my(paste(month, year))} 
    )
  )
}

base_url <- "https://raw.githubusercontent.com/LACMTA/data-safety/main/processed/"

arrest_data <- fromJSON(paste0(base_url, "arrests.json"))
arrest_data <- flatten_json(arrest_data, c("bus", "rail"))

crimes_data <- fromJSON(paste0(base_url, "crimes.json"))
crimes_data <- flatten_json(crimes_data, 
                            c(
                              "bus.total",
                              "bus.persons",
                              "bus.property",
                              "bus.society",
                              "rail.total",
                              "rail.persons",
                              "rail.property",
                              "rail.society"
                              )
                            )

fares_data <- fromJSON(paste0(base_url, "fare.json"))
fares_data <- flatten_json(fares_data, c("bus", "rail"))

ridership_data <- fromJSON(paste0(base_url, "ridership.json"))
ridership_data <- flatten_json(ridership_data, c("bus", "rail"))
```

```{r}
ridership_data |>
  ggplot(aes(x=date, y=count, color=type)) +
  geom_point()
```

```{r}
crimes_data |>
  ggplot(aes(x=date, y=count, color=type)) +
  geom_point()
```

```{r}
arrest_data |>
  ggplot(aes(x=date, y=count, color=type)) +
  geom_point()
```