---
title: "Australia's Frogs (TidyTuesday)"
format: gfm
---

```{r}
library(tidyverse)
library(patchwork)
library(colorspace)
library(ggforce)
library(dplyr)
library(lubridate)
library(broom)
library(sf)
library(rnaturalearth)
```

```{r}
palette <- c(
  "Crinia" = '#E1B248', 
  "Litoria" = '#27D289', 
  "Limnodynastes" = '#B17FBC', 
  "Uperoleia" = '#EA4C70',
  "Adelotus" = '#3072DA',
  "Other" = '#666870'
)
groups <- 5
arrow_style <- arrow(
  angle = 20, length = grid::unit(8, "pt"),
  ends = "first", type = "closed"
)

frogID_data <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/main/data/2025/2025-09-02/frogID_data.csv') |>
  separate_wider_delim(scientificName, delim = " ", names = c("genus", NA), cols_remove=FALSE) |>
  mutate(
    genus_groups=fct_lump_n(genus, n = groups, ties.method="first")
  )

combined_frogs <- add_row(
  frogID_data, 
  eventDate = date("2022-12-01"), 
  timezone="UTC",
  genus="Not Recorded",
  genus_groups="Not Recorded"
)

combined_frogs <-
  combined_frogs |>
  ############# Add seasons #################
  mutate(
    season = case_when(
      ymd(eventDate) >= ymd('2022-12-01') & ymd(eventDate) <= ymd('2023-02-28') ~ "Summer",
      ymd(eventDate) >= ymd('2023-03-01') & ymd(eventDate) <= ymd('2023-05-31') ~ "Autumn",
      ymd(eventDate) >= ymd('2023-06-01') & ymd(eventDate) <= ymd('2023-08-31') ~ "Winter",
      ymd(eventDate) >= ymd('2023-09-01') & ymd(eventDate) <= ymd('2023-11-30') ~ "Spring",
    )
  ) |>
  ############# Correct timezones #################
  mutate(
    timezone = case_when(
      timezone == "GMT+0800" ~ "Australia/Perth",
      timezone == "GMT+0930" ~ "Australia/Adelaide",
      timezone == "GMT+1000" ~ "Australia/Sydney",
      timezone == "GMT+1030" ~ "Australia/Lord_Howe",
      timezone == "GMT+1100" ~ "Etc/GMT-11",
      timezone == "UTC" ~ "Etc/UTC",
    ),
    eventTimestamp = with_tz(force_tzs(ymd_hms(paste(eventDate, eventTime, sep=" ")), tzones = timezone), tzone = "UTC"),
    eventTime =  format(as.POSIXct(eventTimestamp), format = "%H:%M:%S"),
    eventHour = hour(hm(format(round_date(eventTimestamp, unit = "hour"), "%H:%M")))
  )

combined_frogs$season = factor(combined_frogs$season, levels = c("Winter", "Spring", "Summer", "Autumn"))
```


```{r}
#| fig-width: 11
#| fig-height: 5
#| out-width: "100%"

##### SF AUS Base plot ##### 
ds_sf_aus <- ne_states(
  country = "Australia",
  returnclass='sf'
)

##### SF Plot for full AUS map w/ recordings #####
ds_sf_frogs <- st_as_sf(
  combined_frogs |>
    filter(!is.na(decimalLongitude)) |>
    mutate(
      decimalLongitude = round(decimalLongitude),
      decimalLatitude = round(decimalLatitude)
    ) |>
    count(genus_groups, decimalLongitude, decimalLatitude) |>
    group_by(decimalLongitude, decimalLatitude) |> 
    filter(n == max(n)),
  coords = c("decimalLongitude", "decimalLatitude"), 
  crs = 4326
)

sf_aus_full_plot <- 
  ggplot() +
  geom_sf(data = ds_sf_aus) +
  geom_sf(data = ds_sf_frogs, alpha=0.75, aes(color = fct_reorder(genus_groups, n, .desc=TRUE), size = n)) +
  coord_sf(xlim = c(110, 165), ylim=c(-5,-45)) +
  scale_x_continuous(breaks=c(120, 140, 160)) +
  scale_y_continuous(breaks=c(-20, -40, -60)) +
  scale_color_manual(values = palette) +
  guides(
    color = guide_legend(title="Genus", override.aes = list(alpha = 1)),
    size = guide_legend(title="Count", override.aes = list(alpha = 1)),
  ) +
  labs(
    title="1-A) Frog Recordings around Australia in 2023",
    subtitle="Grouped by top genera and reduced based on majority"
  ) +
  theme(
    axis.text.x = element_text(size=10, face = "bold"),
    panel.background = element_blank(),
    panel.grid = element_line(color = "#D7D7D7"),
    panel.spacing = unit(10, "lines"),
    legend.position = "right"
  )

##### SF Plot for faceted frog recordings #####
ds_sf_frog_facet <- 
  st_as_sf(
  combined_frogs |>
    filter(!is.na(decimalLongitude)) |>
    mutate(
      decimalLongitude = round(decimalLongitude),
      decimalLatitude = round(decimalLatitude)
    ) |>
    count(genus, decimalLongitude, decimalLatitude),
  coords = c("decimalLongitude", "decimalLatitude"), 
  crs = 4326
)

sf_aus_facet_plot <-
  ggplot() +
  geom_sf(data = ds_sf_aus) +
  geom_sf(data = ds_sf_frog_facet, alpha=0.5, size=0.75, color="red") +
  coord_sf(xlim = c(80, 190), ylim=c(0,-45)) +
  scale_x_continuous(name="") +
  scale_y_continuous(name="") +
  facet_wrap(~genus) +
  guides(
    color = guide_legend(title="Genus", override.aes = list(alpha = 1)),
    size = guide_legend(title="Count", override.aes = list(alpha = 1)),
  ) +
  labs(
    title="1-B) Facet of frog genera around Australia in 2023",
    subtitle="Red marks indicate instances of recording"
  ) +
  theme(
    axis.text = element_blank(),
    axis.ticks = element_blank(),
    panel.background = element_blank(),
    panel.grid = element_line(color = "#D7D7D7")
  )

sf_aus_full_plot + sf_aus_facet_plot + plot_layout(widths = c(3, 7))
```

```{r}
#| fig-width: 11
#| fig-height: 5
#| out-width: "100%"

##### Cartesian Plot for frequency throughout the year ##### 
cart_total_over_year_plot <-
  combined_frogs |>
  mutate(month= factor(format(eventDate, "%B"), levels = month.name)) |>
  ggplot(aes(month, fill = fct_infreq(genus_groups))) +
  geom_bar() +
  scale_x_discrete(
    name="",
    minor_breaks=NULL
    ) +
  scale_y_continuous(
    name = "Total Recorded",
    breaks=c(0,5000,10000,15000,20000),
    expand = c(0,-10)
  ) +
  guides(fill = "none") +
  coord_polar(start = -0.25, clip = "off") +
  scale_fill_manual(values = palette) +
  labs(
    title="1-C) Total Recordings in per Month in 2023",
    subtitle="No existing data provided for Dec' 23"
  )

##### Faceted Bar Plot for frequency in a day ##### 
season_counts_per_hour_plot <- 
  combined_frogs |>
  filter(genus_groups != "Not Recorded") |> 
  count(eventHour, season, genus_groups, name = "count") |>
  ggplot(aes(eventHour, count, fill = fct_reorder(genus_groups, count, .desc=TRUE))) +
  geom_col() + 
  scale_x_continuous(name="Hour", breaks = c(0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22)) +
  scale_y_continuous(
    name="",
    breaks=c(0,5000,10000,15000,20000)
  ) +
  facet_col(. ~ season) +
  scale_fill_manual(values = palette) +
  labs(
    title="1-D) Total Recordings in a Day",
    subtitle="Faceted by seasons"
  ) +
  guides(fill=guide_legend(title="Genus")) 

(cart_total_over_year_plot + season_counts_per_hour_plot) & 
  theme(
    axis.text.x = element_text(size=10, face = "bold"),
    panel.background = element_blank(),
    panel.grid = element_line(color = "#D7D7D7"),
    legend.position = "right"
  )
```

```{r}
combined_frogs |>
  group_by(scientificName) |>
  summarise(total = n()) |>
  arrange(-total)
```

```{r}
#| fig-width: 11
#| fig-height: 5
#| out-width: "100%"

##### K-Means clustering
km_fit <- 
  combined_frogs |>
  filter(!is.na(decimalLongitude)) |>
  select(decimalLatitude, decimalLongitude) |>
  kmeans(centers = groups+1, nstart = 10)

ds_km_augmented <- 
  st_as_sf(
    km_fit |>
    augment(
      combined_frogs |>
      filter(!is.na(decimalLongitude))
    ),
  coords = c("decimalLongitude", "decimalLatitude"), 
  crs = 4326
)

sf_clusters_plot <-
  ggplot() + 
  geom_sf(data = ds_sf_aus) +
  geom_sf(data = ds_km_augmented, alpha=0.75, size = 2, aes(color = .cluster, shape=genus_groups)) +
  geom_point( 
    data = tidy(km_fit),
    aes(x=decimalLongitude, decimalLatitude, fill = cluster),
    shape = 21, color = "black", size = 4
  ) +
  coord_sf(xlim = c(113, 190), ylim=c(-9,-44)) +
  scale_x_continuous(name="", breaks=c(120, 140, 160)) +
  scale_y_continuous(name="", breaks=c(-20, -40, -60)) +
  guides(
    color="none",
    fill="none"
  )  +
  labs(
    title="2-A) K-Means Clustering of Frog Genera (grouped by top 5)",
    fill="Cluster",
    shape="Genus Group"
  ) +
  theme(
    axis.text.x = element_text(size=10, face = "bold"),
    panel.background = element_blank(),
    panel.grid = element_line(color = "#D7D7D7"),
    panel.spacing = unit(10, "lines"),
    legend.position = "inside",
    legend.position.inside = c(0.80, 0.5),
    legend.box = "horizontal"
  )

sf_genus_shown_plot <-
  ggplot() + 
  geom_sf(data = ds_sf_aus) +
  geom_sf(data = ds_km_augmented, alpha=0.75, size = 2, aes(color = genus_groups, shape=genus_groups)) +
  geom_point( 
    data = tidy(km_fit),
    aes(x=decimalLongitude, decimalLatitude, fill = cluster),
    shape = 21, color = "black", size = 4
  ) +
  coord_sf(xlim = c(113, 190), ylim=c(-9,-44)) +
  scale_x_continuous(name="", breaks=c(120, 140, 160)) +
  scale_y_continuous(name="", breaks=c(-20, -40, -60)) +
  scale_color_manual(values=palette) +
  guides(shape="none")  +
  labs(
    title="2-B) Actual spread of frog genera (grouped) vs centroids",
    fill="Cluster",
    color="Genus Group"
  ) +
  theme(
    axis.text.x = element_text(size=10, face = "bold"),
    panel.background = element_blank(),
    panel.grid = element_line(color = "#D7D7D7"),
    panel.spacing = unit(10, "lines"),
    legend.position = "inside",
    legend.position.inside = c(0.80, 0.5),
    legend.box = "horizontal"
  )
  
(sf_clusters_plot + sf_genus_shown_plot)
```
